### PR TITLE
fix: cards should have the same size

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/firstrunwizard/issues/1342

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Review by susnux — APPROVED** [review]
looks good!

**Comment by susnux** [comment]
> backport to stable28

Was it already added there? I thought we touched it only for 29+?

**Comment by szaimen** [comment]
> > backport to stable28
> 
> Was it already added there? I thought we touched it only for 29+?

Ah right. I don't remember 🙈

**Comment by szaimen** [comment]
I guess wel' see son ;)

**Comment by szaimen** [comment]
Is the backport bot down?

**Pull request merged**
