### PR TITLE
Use target="_blank" and rel="noreferrer noopener"

### LINKED ISSUE #79: Open links in new tab
The new popup is great, however, clicking a link break UX as it open the link in the same page. Coming back does not display the popup anymore. User might feel loosing something.

Expected behavior: open each link from the popup in a new tab.

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #79

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> The backport to stable14 failed. Please do this backport manually.

@juliushaertl Mind to do it?

**Comment by jancborchardt** [comment]
Good stuff, thanks @juliushaertl! :)

**Pull request merged**
