### PR TITLE
Revert removing static js files

### PR DESCRIPTION
**Pull request by tcitworld**
Partially reverts commit 40b0ea948c4fe3491b8bb0e01b176cfab8263af7, which removed some static js files by accident

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Review by szaimen — CHANGES_REQUESTED** [review]
Looks like something else is the problem. Maybe a missing wepback configuration or something?

**Comment by tcitworld** [comment]
That removed my changes :p

**Comment by szaimen** [comment]
> That removed my changes :p

I know, however Node fails with your change :P

**Comment by tcitworld** [comment]
There we go.

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
