### PR TITLE
disable social recommendation

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/31883

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by Pytal — APPROVED** [review]
Add a comment to explain reasoning?

**Comment by szaimen** [comment]
> Add a comment to explain reasoning?

I think I'll rather leave that out as I am not so sure what to write there...

---

cc @AndyScherzinger please merge when you are fine with this PR. Thanks! :)

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
@Pytal the reasoning is that we currently focus on other areas and apps thus promoting an app that is currently not working with 22+ should be prevented.

**Comment by AndyScherzinger** [comment]
Thanks @szaimen 🙏🏼

**Pull request merged**
