### PR TITLE
Move personal setting to the app

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Server PR https://github.com/nextcloud/server/pull/5591

### CODE REVIEW

**Comment by nickvergessen** [comment]
The page of the app is currently very empty.
Anyone has any idea what we could do there? Maybe expand the info we show directly instead of having a button to open the wizard?

@blizzz @MorrisJobke @jancborchardt @jospoortvliet 

> nextcloud_-_2017-07-03_12 43 21

**Comment by jancborchardt** [comment]
Yeah, let's definitely put the whole info of the wizard directly there. It also has info on the documentation and syncing Calendar & Contacts. :)

**Comment by jancborchardt** [comment]
@nickvergessen can you open a follow-up pull request for moving the whole content of the wizard into that settings section? :)

**Comment by nickvergessen** [comment]
See #43

**Pull request merged**
