### PR TITLE
fix: Remove legacy code that caused errors

### PR DESCRIPTION
**Pull request by susnux**
* Fix https://github.com/nextcloud/firstrunwizard/issues/1247

The code was not used with 28+ anymore and removed in 29+ so we also need to remove for 28.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Not familiar with this, so removing myself

**Review by szaimen — APPROVED** [review]
🐘

**Comment by Pytal** [comment]
CI is related 🧐

**Comment by susnux** [comment]
> CI is related 🧐

@Pytal should be fixed

**Comment by Pytal** [comment]
Still red https://github.com/nextcloud/firstrunwizard/actions/runs/9626238630/job/26551973859?pr=1260 :(

**Pull request merged**
