### PR TITLE
Extend reasons for email address

### PR DESCRIPTION
**Pull request by nickvergessen**
It's a bit confusing to be asked to enter an email address to be able to reset a password while the backend does not allow this at all (LDAP, SAML, ....)

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Could we maybe additionally check for the `OCP\User\Backend\ISetPasswordBackend` interface on the backend?

**Comment by nickvergessen** [comment]
Added

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
