### PR TITLE
Allow to configure a custom slide list

### PR DESCRIPTION
**Pull request by juliushaertl**
Allow specifying a custom list of the slides to use in the wizard though app config

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:elephant: 
Nice

**Comment by robrecord** [comment]
So how do you use it? No documentation anywhere

**Comment by Juoper** [comment]
How can i edit the slides?

**Comment by alex-pub** [comment]
For all that were asking on how to set up custom slides—
The documentation is sorely lacking and there is no UI (to my knowledge) to allow you to configure the slides, so I had to do a bit of digging through the code to figure out how it's implemented. To save some time for others who stumble upon this page:

- Slides can be set in the app config for the `firstrunwizard` app, as `slides` config parameter
- It should be a comma-delimited string denoting individual slides and their order
- If not defined, it defaults to: `video,values,apps,clients,final` (see [WizardController.php#L65](https://github.com/nextcloud/firstrunwizard/blob/98da5faf5440461ad3c06f16f105e35a5920b810/lib/Controller/WizardController.php#L65))

The easiest way to change/set the value is via [`occ` ](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html) e.g.,: `occ config:app:set firstrunwizard slides --value=values,final`
to skip the video and app link slides.

If you want to add your own slides, from what I can see it's not possible atm. short of editing `WizardController.php` directly (in your nextcloud's `apps/firstrunwizard/lib`) to add more slides (they are defined in the `show()` function), or at least editing the already defined slides themselves (they are presented as individual php files @ `apps/firstrunwizard/templates`).

Now on to figure out how to get all the templates to run 'externally', loaded from a shared store among all users... 😅

**Pull request merged**
