### PR TITLE
remove smiley

### PR DESCRIPTION
**Pull request by schiessle**
I think that's not the right place for a smiley. Let's remove it.

cc @jancborchardt @MorrisJobke

### CODE REVIEW

**Comment by schiessle** [comment]
cc @nickvergessen as discussed yesterday

**Comment by nickvergessen** [comment]
👍

**Comment by jancborchardt** [comment]
Don’t you think the exclamation mark is a bit »shouty« without the smiley? ;)

**Comment by schiessle** [comment]
> Don’t you think the exclamation mark is a bit »shouty« without the smiley? ;)

Maybe but the smiley looks really unprofessional. Feel free to open a follow up PR to adjust the text however you wish, but please without a smiley 😃

**Comment by jancborchardt** [comment]
@schiessle next profile picture also without smile please, very unprofessional ;)

**Pull request merged**
