### PR TITLE
chore: update workflows from templates

### PR DESCRIPTION
**Pull request by nextcloud-command**
This PR was automatically generated by the workflow dispatcher
Please check that there are no reverted changes before merging ⚠

See templates in https://github.com/nextcloud/.github

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
Needs adjustments

**Comment by skjnldsv** [comment]
I think it needs fixing, but not the workflow.
8.2 seems broken with `firstrunwizard`

**Comment by szaimen** [comment]
Fixed the phpunit test. Now only the info.xml needs to be updated in https://github.com/nextcloud/appstore/pull/1052

**Review by szaimen — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
> Can someone force-merge? CI failure unrelated

Needs an admin

**Pull request merged**
