### PR TITLE
New intro files

### PR DESCRIPTION
**Pull request by skjnldsv**
```
# mediainfo Nextcloud.mp4

General
Complete name                            : Nextcloud.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 956 KiB
Duration                                 : 10 s 6 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 783 kb/s
Writing application                      : Lavf58.76.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 10 s 0 ms
Bit rate                                 : 689 kb/s
Maximum bit rate                         : 1 000 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.013
Stream size                              : 841 KiB (88%)
Writing library                          : x264 core 161 r3039 544c61f
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=15.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 10 s 6 ms
Source duration                          : 10 s 27 ms
Bit rate mode                            : Variable
Bit rate                                 : 87.2 kb/s
Maximum bit rate                         : 128 kb/s / 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 107 KiB (11%)
Source stream size                       : 107 KiB (11%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
mdhd_Duration                            : 10005
```

```
# mediainfo Nextcloud.webm

General
Complete name                            : Nextcloud.webm
Format                                   : WebM
Format version                           : Version 2
File size                                : 817 KiB
Duration                                 : 10 s 8 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 669 kb/s
Writing application                      : Lavf58.76.100
Writing library                          : Lavf58.76.100

Video
ID                                       : 1
Format                                   : VP8
Codec ID                                 : V_VP8
Duration                                 : 10 s 0 ms
Bit rate                                 : 522 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.010
Stream size                              : 637 KiB (78%)
Writing library                          : Lavc58.134.100 libvpx
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
VENDOR_ID                                : [0][0][0][0]

Audio
ID                                       : 2
Format                                   : Vorbis
Format settings, Floor                   : 1
Codec ID                                 : A_VORBIS
Duration                                 : 10 s 8 ms
Bit rate mode                            : Variable
Bit rate                                 : 112 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Delay relative to video                  : -3 ms
Stream size                              : 137 KiB (17%)
Writing application                      : Lavc58.134.100
Writing library                          : libVorbis (Reducing Environment) (20200704 (Reducing Environment))
Language                                 : English
Default                                  : Yes
Forced                                   : No
VENDOR_ID                                : [0][0][0][0]

```

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Encoding matches with the old files :+1:

**Comment by jospoortvliet** [comment]
Works for me!

**Pull request merged**
