### PR TITLE
Migrate personal setting page to vue

### PR DESCRIPTION
**Pull request by susnux**
* Fix https://github.com/nextcloud/firstrunwizard/issues/1231

The page was using a removed script, so I ported it to vue completly.
But maybe this better belongs to server core?

### CODE REVIEW

**Review by szaimen — COMMENTED** [review]
I tested it and it looks mostly fine but I noticed two things:
- the icon has the wrong color
- the server address does not seem to be correct

image

**Comment by szaimen** [comment]
I just tested this again.

> * the icon has the wrong color

This is still the case but the other issue seems to be fixed :)

However this button does not seem to work:
image

**Comment by susnux** [comment]
@szaimen both issues should be now resolved

**Review by szaimen — APPROVED** [review]
Just tested again and works :)
But didnt review the code

**Pull request merged**
