### PR TITLE
disable fade-out because of accessbility reasons

### PR DESCRIPTION
**Pull request by szaimen**
follow up to https://github.com/nextcloud/viewer/pull/1064

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@juliushaertl looks like the compile command fails. Do you have any ideas why?

<details>
<summary>Here are the logs</summary>

```
npm ERR!   rm -rf "Release/sass.a" && cp -af "Release/obj.target/src/sass.a" "Release/sass.a"
npm ERR!   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/runner/.node-gyp/16.13.0/include/node -I/home/runner/.node-gyp/16.13.0/src -I/home/runner/.node-gyp/16.13.0/deps/openssl/config -I/home/runner/.node-gyp/16.13.0/deps/openssl/openssl/include -I/home/runner/.node-gyp/16.13.0/deps/uv/include -I/home/runner/.node-gyp/16.13.0/deps/zlib -I/home/runner/.node-gyp/16.13.0/deps/v8/include -I../node_modules/nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++14 -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
npm ERR! make: Leaving directory '/home/runner/work/firstrunwizard/firstrunwizard/node_modules/node-sass/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/opt/hostedtoolcache/node/16.13.0/x64/bin/node',
npm ERR! gyp verb cli   '/home/runner/work/firstrunwizard/firstrunwizard/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` succeeded python2 /usr/bin/python2
npm ERR! gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.0
npm ERR! gyp verb command install [ '16.13.0' ]
npm ERR! gyp verb install input version string "16.13.0"
npm ERR! gyp verb install installing version: 16.13.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version not already installed, continuing with install 16.13.0
npm ERR! gyp verb ensuring nodedir is created /home/runner/.node-gyp/16.13.0
npm ERR! gyp verb created nodedir /home/runner/.node-gyp
npm ERR! gyp http GET https://nodejs.org/download/release/v16.13.0/node-v16.13.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.13.0/node-v16.13.0-headers.tar.gz
npm ERR! gyp verb extracted file from tarball include/node/common.gypi
npm ERR! gyp verb extracted file from tarball include/node/config.gypi
npm ERR! gyp verb extracted file from tarball include/node/node.h
npm ERR! gyp verb extracted file from tarball include/node/node_api.h
npm ERR! gyp verb extracted file from tarball include/node/js_native_api.h
npm ERR! gyp verb extracted file from tarball include/node/js_native_api_types.h
npm ERR! gyp verb extracted file from tarball include/node/node_api_types.h
npm ERR! gyp verb extracted file from tarball include/node/node_buffer.h
npm ERR! gyp verb extracted file from tarball include/node/node_object_wrap.h
npm ERR! gyp verb extracted file from tarball include/node/node_version.h
npm ERR! gyp verb extracted file from tarball include/node/v8-internal.h
npm ERR! gyp verb extracted file from tarball include/node/v8-platform.h
npm ERR! gyp verb extracted file from tarball include/node/v8-profiler.h
npm ERR! gyp verb extracted file from tarball include/node/v8.h
npm ERR! gyp verb extracted file from tarball include/node/v8config.h
npm ERR! gyp verb extracted file from tarball include/node/v8-version.h
npm ERR! gyp verb extracted file from tarball include/node/libplatform/libplatform-export.h
npm ERR! gyp verb extracted file from tarball include/node/libplatform/libplatform.h
npm ERR! gyp verb extracted file from tarball include/node/libplatform/v8-tracing.h
npm ERR! gyp verb extracted file from tarball include/node/cppgc/common.h
npm ERR! gyp verb extracted file from tarball include/node/uv.h
npm ERR! gyp verb extracted file from tarball include/node/uv/aix.h
npm ERR! gyp verb extracted file from tarball include/node/uv/android-ifaddrs.h
npm ERR! gyp verb extracted file from tarball include/node/uv/bsd.h
npm ERR! gyp verb extracted file from tarball include/node/uv/darwin.h
npm ERR! gyp verb extracted file from tarball include/node/uv/linux.h
npm ERR! gyp verb extracted file from tarball include/node/uv/os390.h
npm ERR! gyp verb extracted file from tarball include/node/uv/posix.h
npm ERR! gyp verb extracted file from tarball include/node/uv/stdint-msvc2008.h
npm ERR! gyp verb extracted file from tarball include/node/uv/sunos.h
npm ERR! gyp verb extracted file from tarball include/node/uv/threadpool.h
npm ERR! gyp verb extracted file from tarball include/node/uv/unix.h
npm ERR! gyp verb extracted file from tarball include/node/uv/win.h
npm ERR! gyp verb extracted file from tarball include/node/uv/errno.h
npm ERR!
Error: Process completed with exit code 1.
```

</details>

**Comment by juliushaertl** [comment]
Could be a newer node version where libsass is not released as prebuilt binaries and the manual build is failing in the action due to a missing dependency.

**Comment by skjnldsv** [comment]
> Could be a newer node version where libsass is not released as prebuilt binaries and the manual build is failing in the action due to a missing dependency.

image

We should have used `^14.0.0` and not `>= 14.0.0`

**Comment by juliushaertl** [comment]
Oh, right, i just compared with server and it had the same so I didn't check that further https://github.com/nextcloud/server/blob/master/package.json#L126-L129

**Pull request merged**
