### PR TITLE
fix: Make "share on" entries same width

### PR DESCRIPTION
**Pull request by susnux**
before|after
---|---
Screenshot 2024-08-28 at 18-53-32 Personal info - Personal settings - Nextcloud|Screenshot 2024-08-28 at 18-58-54 Personal info - Personal settings - Nextcloud

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM :)

**Comment by szaimen** [comment]
However noticed something else:
image
Shall I open a new issue?

**Comment by susnux** [comment]
> Shall I open a new issue?

yes I would say not directly related to this :)

**Pull request merged**
