### PR TITLE
[stable10] design improvements

### PR DESCRIPTION
**Pull request by jancborchardt**
Backport of https://github.com/nextcloud/firstrunwizard/pull/5 

@schiessle @enoch85 @oparoz please review :)

### CODE REVIEW

**Comment by enoch85** [comment]
:+1: Looks good to me. Not tested.

**Comment by jancborchardt** [comment]
@enoch85 then please test ;)

**Comment by schiessle** [comment]
tested, works :+1:

**Comment by MorrisJobke** [comment]
Tests also fail on stable10 -> merge

**Pull request merged**
