### PR TITLE
fix overlapping buttons

### PR DESCRIPTION
**Pull request by szaimen**
This is best reviewed like this: https://github.com/nextcloud/firstrunwizard/pull/651/files?diff=unified&w=1

## Desktop
| Before | After |
|---|---|
| image | image |

## Mobile
| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e FIRSTRUNWIZARD_BRANCH=enh/noid/fix-overlapping-buttons \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Not fod of the migration of the primary button to the left. I would have maybe made the main content scrollable/shrinkable and the button fixed at the bottom :thinking:

**Comment by szaimen** [comment]
> Not fod of the migration of the primary button to the left.

Just pushed a new commit that switches the sides which is a good solution as well, imo.

Please have a look at the updated screenshots :)

**Review by juliushaertl — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
sheduled for 22.2.4 - https://github.com/nextcloud/firstrunwizard/pull/653

**Pull request merged**
