### PR TITLE
Move to shared configs

### PR DESCRIPTION
**Pull request by juliushaertl**
Signed-off-by: Julius Härtl <jus@bitgrid.net>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by artonge — APPROVED** [review]
Maybe update `.gitattributes` to add the licence file and `package-lock.json` ?

```
/js/firstrunwizard-main.js.LICENSE.txt binary
package-lock.json binary
```

**Comment by artonge** [comment]
Eslint action is failing because it uses npm6, this needs to be updated: https://github.com/nextcloud/firstrunwizard/blob/master/.github/workflows/lint.yml#L22

**Comment by juliushaertl** [comment]
OK, the xml linter is not happy about the empty route that is used here because the about dialog is triggered by js only, will see how I can fix that.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/firstrunwizard/pull/648

**Pull request closed without merging**
