### PR TITLE
Add a notification as a reminder to fill out the profile information

### LINKED ISSUE #17: People should be prompted to input info (like mail, name etc) on first run
@ryno83 @nextcloud/designers let's continue discussing here how that could look like. :)

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #17 

Also comes with the following improvements:
* only slows down the page when we visit the files app now (no more ocs and webdav slow down)
* cleaned up the code to be Nextcloud 10 state of the art without the use of private apis

cc @jancborchardt @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and still works 👍

**Comment by MorrisJobke** [comment]
* [ ] notification doesn't show up

**Comment by nickvergessen** [comment]
Fixed

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
