### PR TITLE
Upgrade @nextcloud/vue from 5.4.0 to 7.5.0

### PR DESCRIPTION
**Pull request by Pytal**
Upgrade https://github.com/nextcloud/nextcloud-vue + adapt markup

Fix "Maximum call stack size exceeded" error from focus-trap when opening from menu entry

### Related

- https://github.com/nextcloud/nextcloud-vue/pull/3690

### CODE REVIEW

**Comment by Pytal** [comment]
> Works in my testing. However the left arrow is not usable with keyboard-enter. (it brings you not to the former slide back and instead displays the same slide again).

Fixed in https://github.com/nextcloud/nextcloud-vue/pull/3690

**Review by szaimen — APPROVED** [review]
LGTM then for now if it gets fixed in a follow-up

**Comment by Pytal** [comment]
> LGTM then for now if it gets fixed in a follow-up

Let's do a bump after the fix is released then

- [ ] Bump `@nextcloud/vue` with fix https://github.com/nextcloud/nextcloud-vue/pull/3690

**Pull request merged**
