### PR TITLE
fix: Adjust styles for Nextcloud 30 (default heading styles)

### PR DESCRIPTION
**Pull request by susnux**
* Resolves https://github.com/nextcloud/firstrunwizard/issues/1283

Adjusted the headings for https://github.com/nextcloud/server/pull/43640/files

### CODE REVIEW

**Comment by szaimen** [comment]
> They are, but we need to adjust, as our h3 here e.g. for cards would be too big. they are fine if you use h2-h6 but we only have h2 and h3

I see. then lets do it like that

**Review by szaimen — CHANGES_REQUESTED** [review]
I just tested this and the headings still look a bit big?
image

**Comment by susnux** [comment]
Maybe we should also change the styles on server again to not use the h1 styles for h2 ... but just use h2 for h2 etc.
Because for non text documents a that big h2 makes no sense and we need to adjust the styles everywhere.

**Comment by szaimen** [comment]
Fyi @nextcloud/designers

**Comment by Pytal** [comment]
Shoule this get in @susnux?

**Comment by susnux** [comment]
> Should this get in @susnux?

we need to do so, probably adjusting the size a bit more

**Comment by AndyScherzinger** [comment]
@susnux if it is an improvement over the current state than I'd say let's merge as-is and have a follow-up. If it doesn't improve the situation in the current state of the PR, than let's leave it open for now.

**Comment by susnux** [comment]
@AndyScherzinger  yes we need this otherwise it does not properly fit Nextcloud 30

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Thanks @susnux - merged. I think daily pulls master-branch also for this app. Hence we can look at it tomorrow 👍

**Pull request merged**
