### PR TITLE
add headings for slides

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/firstrunwizard/issues/107

| 1 | 2 | 3 | 4 |
|---|---|---|---|
| image | image | image | image |

### CODE REVIEW

**Review by jancborchardt — CHANGES_REQUESTED** [review]
I'd say just using the position of the slogan (on the blue background above) is nicer for the header. Then we don't use more space, and the text is not just all the same on all pages.

Text I'd suggest for each slide:
1. A safe home for your data (like now but with capital A)
2. Extend your cloud (like the page title)
3. Stay in sync (like the page title)
4. Get support or participate (as you suggested)

**Comment by szaimen** [comment]
> * Extend your cloud (like the page title)
> * Stay in sync (like the page title)
> * Get support or participate (as you suggested)

Should be adjusted

**Comment by jancborchardt** [comment]
We need to get the slides simpler though. :) I think having the heading in the blue part will be fine. We can also bold it for more presence.

But adding more text makes it quite cluttered.

**Comment by szaimen** [comment]
all right. Let me investigate then how we could add this to the header...

**Comment by szaimen** [comment]
@jancborchardt I investigated a bit and due to how the app is currently built: Rendering in Vue but templates in PHP, I currently don't see an good way to insert a title from the template into the header of the modal (despite hacky ways) without rewriting quite some code.

So would it be okay to leave it in the body for now or do we rather want to postpone this?

**Review by jancborchardt — APPROVED** [review]
Let's go with this for now :)

**Pull request merged**
