### PR TITLE
fix: Fix focus lost to body when closing firstrunwizard

### PR DESCRIPTION
**Pull request by Pytal**
- Fix https://github.com/nextcloud/firstrunwizard/issues/1072

### CODE REVIEW

**Comment by szaimen** [comment]
I tested this and it doesnt seem to work since the menu seems to close when you open the firstrunwizard:

https://github.com/nextcloud/firstrunwizard/assets/42591237/f1b3dd60-1f18-4d5c-a0b7-f3921ca0e956

**Review by JuliaKirschenheuter — APPROVED** [review]
In my eyes it works well, thank you!

But actually this app is disabled and it was decided to leave `firstrunwizard` disabled

**Comment by Pytal** [comment]
> I tested this and it doesnt seem to work since the menu seems to close when you open the firstrunwizard:

Maybe not intuitive but the menu is supposed to close and the focus returns to the avatar button

> But actually this app is disabled and it was decided to leave `firstrunwizard` disabled

Right!

**Comment by szaimen** [comment]
> Maybe not intuitive but the menu is supposed to close and the focus returns to the avatar button

Yes, definitely not intuitive. Shouldnt the menu stay open?

**Comment by szaimen** [comment]
> > Yes, definitely not intuitive. Shouldnt the menu stay open?
> 
> Nope, was discussed already that only when the menu is open it retains focus and is otherwise closed for a11y

All right

**Pull request merged**
