### PR TITLE
Extract buttons from pages so the animation does not affect t…

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Review by szaimen — COMMENTED** [review]
I would like to block this since layout change breaks the responsive layout

**Comment by szaimen** [comment]
@marcoambrosini will you be able to work on this? I think the idea was good but if broke the responsive layout

**Review by marcoambrosini — APPROVED** [review]

**Comment by szaimen** [comment]
LGTM now and can be merged as soon as all CI is green :)

**Pull request merged**
